# Auto Regression Moving Average(ARMA)
mostly used in stationary models

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
temp_data=pd.read_csv('dailymintemperatures (1)''.csv')

In [3]:
temp_data.head()

Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [4]:
temp_data['lag']=temp_data['Temp'].shift(1)

In [5]:
temp_data['resid']=temp_data['Temp']-temp_data['lag']

In [6]:
temp_data.head()

Date  Temp   lag  resid
0  1981-01-01  20.7   NaN    NaN
1  1981-01-02  17.9  20.7   -2.8
2  1981-01-03  18.8  17.9    0.9
3  1981-01-04  14.6  18.8   -4.2
4  1981-01-05  15.8  14.6    1.2

In [7]:
temp_data.shape

(3650, 4)

In [8]:
len(temp_data['resid'])

3650

In [9]:
x=temp_data['resid'].values
x

array([ nan, -2.8,  0.9, ..., -0.1,  2.2, -2.7])

In [16]:
train,test=x[1:len(temp_data)-7],x[len(temp_data)-7:]

In [17]:
train

array([-2.8,  0.9, -4.2, ...,  0.1,  0.7, -3.9])

In [18]:
train.shape

(3642,)

In [20]:
test

array([ 2.9,  1.7, -0.6, -0.4, -0.1,  2.2, -2.7])

In [19]:
test.shape

(7,)

# fitting the model

In [23]:
from statsmodels.tsa.ar_model import AutoReg

In [25]:
model=AutoReg(train,lags=29)
model_fit=model.fit()

In [26]:
len(train)+len(test)

3649

In [27]:
test

array([ 2.9,  1.7, -0.6, -0.4, -0.1,  2.2, -2.7])

In [28]:
train

array([-2.8,  0.9, -4.2, ...,  0.1,  0.7, -3.9])

In [29]:
pred_resid=model_fit.predict(start=len(train),end=len(train)+len(test)-1)
pred_resid

array([ 2.00498584,  1.26419221,  0.51086935, -0.25168707, -0.122054  ,
        0.07750947,  0.05559998])

In [30]:
temp_data.lag[temp_data.shape[0]-7:]

3643    10.0
3644    12.9
3645    14.6
3646    14.0
3647    13.6
3648    13.5
3649    15.7
Name: lag, dtype: float64

In [31]:
predictions=temp_data.lag[temp_data.shape[0]-7:]+pred_resid
predictions

3643    12.004986
3644    14.164192
3645    15.110869
3646    13.748313
3647    13.477946
3648    13.577509
3649    15.755600
Name: lag, dtype: float64

In [32]:
x=temp_data['Temp']
x

0       20.7
1       17.9
2       18.8
3       14.6
4       15.8
        ... 
3645    14.0
3646    13.6
3647    13.5
3648    15.7
3649    13.0
Name: Temp, Length: 3650, dtype: float64

In [33]:
type(x)

pandas.core.series.Series

In [34]:
train,test=x[1:len(x)-7],x[len(x)-7:]

In [35]:
test

3643    12.9
3644    14.6
3645    14.0
3646    13.6
3647    13.5
3648    15.7
3649    13.0
Name: Temp, dtype: float64

In [36]:
from sklearn.metrics import mean_squared_error

In [37]:
import numpy as np

In [38]:
rmse=np.sqrt(mean_squared_error(test,predictions))
print('rmse:',rmse)

rmse: 1.4315720577910878
